///<reference types="cypress"/>
describe('template spec', function() {
  it.skip('passes', () => {
    cy.visit('http://www.uitestpractice.com/')
    cy.get('body > div.navbar.navbar-inverse.navbar-fixed-top > div > div.navbar-collapse.collapse > ul > li:nth-child(3) > a').click()
    cy.get(':nth-child(5) > :nth-child(2) > input').check()
    cy.get(':nth-child(5) > :nth-child(3) > input').check()
    cy.get(':nth-child(5) > :nth-child(4) > input').check()
    cy.get('#sel1').select('Andorra')
    cy.get('#firstname').type('vamshi')
    cy.get(':nth-child(3) > :nth-child(2) > input').click()
    cy.get('#sel1').select('Bahrain')
    cy.log(cy.title())
  })
  it.only('frmaes',()=>{
	   cy.visit('http://www.uitestpractice.com/')
	   cy.screenshot("homepagesss")
	  cy.get(':nth-child(7) > a').click()
	  const iframe=cy.get(':nth-child(4) > iframe')
	  .its('0.contentDocument.body')
	  .should('be.visible')
	  .then(cy.wrap)
	  iframe.find('#name').click().type("vamshidhar")
	  cy.get('.body-content > :nth-child(1) > :nth-child(6) > a').invoke('removeAttr','target').click()
	  cy.go(-1)
	  cy.get('.nav > :nth-child(6) > a').trigger('mouseover').click()
	// cy.lost('Controls')
	cy.get(':nth-child(4) > a').click()
	// cy.get("[style='position: relative;']").dblclick()
	 cy.doublec("[name='dblClick']")
  })
})